### ISSUE TITLE
Update UI to add a "Save" button on topics

### ISSUE THREAD

**Issue by cindyjiang-027** [CMU-313/nodebb-f24-the-bots#6]
### Description

**Estimated Effort:** 6 hours

**Dependencies:** #3 #4 #5 

**Acceptance Criteria:** A “Save” button is added to the topic view. The button correctly reflects whether the topic is already saved. UI/UX is consistent with the rest of the platform.

**Comment by swaeliu** [comment]
![Image](https://github.com/user-attachments/assets/e25793e3-0574-434b-9cb0-096bbe61656c)

Front end change to implement this functionality was developed locally. A save button has been added.
